[project]
name = "bank-deposit-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[dependency-groups]
data = [
    "dvc>=3.63.0",
    "ipykernel>=7.1.0",
    "mlflow>=3.5.1",
    "xgboost-cpu>=3.1.1",
]

